### ISSUE TITLE
Explain code generation by relm4_macros::widget

### ISSUE THREAD

**Issue by tronta** [AaronErhardt/AaronErhardt.github.io#31]
You are writing that the struct is automatically generated:
https://aaronerhardt.github.io/relm4-book/book/widget_macro.html#whats-different

How will it look like? Can one define the names? How can one access it? Maybe I have missed this part.

**Comment by AaronErhardt** [comment]
For example for the "simple" example the generated struct looks like this

```rust
#[allow(dead_code)]
struct AppWidgets {
    _gtk_applicationwindow_4: gtk::ApplicationWindow,
    _gtk_box_3: gtk::Box,
    _gtk_button_0: gtk::Button,
    _gtk_button_with_label_1: gtk::Button,
    _gtk_label_2: gtk::Label,
}
```

So the macro generates a field for every widget. If the widget is named it gets that name and if not a name is generated. The generated names look like _gtk_widget_NUM. But if you want to access widgets you should always name widgets: https://aaronerhardt.github.io/relm4-book/book/widget_macro_reference.html#add-widgets

**Comment by AaronErhardt** [comment]
Btw. you can use [cargo-expand](https://github.com/dtolnay/cargo-expand) to show the code generated by the macro.

**Comment by tronta** [comment]
Cool. 
It might make sense to add this information to the  macro reference. At least it's a reference.

The part with the naming and accessing should be more explicit in the documentation as this is a essential part. Currently it's pretty hidden (at least for people like me :smile: )

What do you think?

**Comment by AaronErhardt** [comment]
I've added a new chapter to the book: https://aaronerhardt.github.io/relm4-book/book/widget_macro_expansion.html

What do you think?

**Comment by tronta** [comment]
I like it. Thanks a lot.

The only part which looked to me pretty complex was the "Generated UI" updates part.
It might be helpful to provide a few sentences what this function does.
And is there maybe the if clause missing above the first line?

**Comment by AaronErhardt** [comment]
No, the if clause should be in the code example. IMO it's somewhat unfortunate that format! and println! are expanded, too. That makes the code look different despite it being quite simple. I think I will reorder it so that the both update rules come after each other with their code from the macro and are also explained a bit better.

Technically, I could manually remove the expansion from the println! and format! macros. Would that help? At least the code from the macro would then look a lot more like the expansion.

**Comment by tronta** [comment]
Imho it would be great if you could revert the expansion of println! and co. It just distracts from the relevant parts.

**Comment by AaronErhardt** [comment]
The whole chapter should be much clearer and the "Generated UI updates" paragraph as well: https://aaronerhardt.github.io/relm4-book/book/widget_macro_expansion.html#generated-ui-updates

**Comment by tronta** [comment]
Is the macro `send!()` explained some where? Maybe I missed it.

**Comment by tronta** [comment]
Otherwise looks good!

**Comment by AaronErhardt** [comment]
Originally, I explained it in the first chapter but I found it rather distracting there, so I removed the section. The macro is pretty simple though. It's just some syntactical sugar that sends and then unwraps the result (because as long you don't drop the receiver it will never return an error and the receiver is usually kept alive by Relm4).

But I think I will add a short section to the macro reference.

**Comment by tronta** [comment]
I think this is a good idea.

**Comment by AaronErhardt** [comment]
I've added it here: https://aaronerhardt.github.io/relm4-book/book/widget_macro_reference.html#the-send-macro

**Comment by tronta** [comment]
cool. thx.
